#! /bin/sh

: ${MAKE=make}
: ${srcdir=.}
: ${SED="../sed/sed"}

makefile="$srcdir/Makefile.tests"
test=`echo "$@"| sed 's,.*/,,'`

exitcode=0
$MAKE SED="$SED" srcdir="$srcdir" -f "$makefile" $test || exitcode=$?
test -f $test.skip && exitcode=77
rm -f $test.skip
exit $exitcode
