#! /bin/sh

# The test harness, used invoked through LOG_COMPILER
# in testsuite/local.mk .
# The two auxialiary programs (get-mb-cur-max and test-mbrtowc)
# need to be compiled, but they are not stand-alone tests -
# so they are skipped.

. "${srcdir=.}/testsuite/init.sh"; path_prepend_ ./sed

# Strip any leading directory names from the test name
test=${1##*/}

# Skip the utility programs, they are not standalone tests
case "$test" in
    get-mb-cur-max|test-mbrtowc)
	# exit code 77 is automake's code for 'skip'.
	exit 77
	;;
    *)
	# should not happen. If it does - a sed developer
	# made some mistake in 'testsuite/local.mk'.
	echo "internal error: unknown test '$test' in $0" >&2 ;
	exit 1
	;;
esac
